#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor2,          xMotor,        tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor7,          armMotor,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor9,          pickMotor1,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor12,         pickMotor2,    tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

static int movethreshold=15;

void remove()
{
	int x=vexRT[ChC];
	int y=vexRT[ChD];
	int z=vexRT[ChB];

	if(abs(x)>movethreshold&&abs(x)>abs(y))
	{
		motor[xMotor]=x;
	}
	else if(abs(y)>movethreshold&&abs(y)>abs(x)&&abs(z)<movethreshold)
	{
		motor[leftMotor]=y;
		motor[rightMotor]=y;
	}
	else if(abs(y)>movethreshold&&abs(y)>abs(x)&&abs(z)>movethreshold)
	{
		motor[leftMotor]=y+z;
		motor[rightMotor]=y-z;
	}
	else if(abs(z)>movethreshold)
	{
		motor[leftMotor]=z;
		motor[rightMotor]=-z;
	}
	else
	{
		motor[leftMotor]=0;
		motor[rightMotor]=0;
		motor[xMotor]=0;
	}
}

void pick()
{
	motor[pickMotor1]=vexRT[BtnRUp]*100-vexRT[BtnRDown]*100;
	motor[pickMotor2]=vexRT[BtnRUp]*100-vexRT[BtnRDown]*100;
}

void hang()
{
	motor[armMotor]=vexRT[BtnLUp]*100-vexRT[BtnLDown]*100;
}
task main()
{
	while(1)
	{
		remove();
		pick();
		hang();
	}
}
