#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor2,          zMotor,        tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor7,          larmMotor,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor9,          pickMotor,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor12,         rarmMotor,     tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

static int threshold=15;
void remove()
{
	int x=vexRT[ChC];
	int y=vexRT[ChD];
	int z=vexRT[ChB];

	if(abs(x)>threshold&&abs(x)>abs(y))
	{
		motor[zMotor]=x;
	}
	else if(abs(y)>threshold&&abs(y)>abs(x)&&abs(z)<threshold)
	{
		motor[leftMotor]=y;
		motor[rightMotor]=y;
	}
	else if(abs(y)>threshold&&abs(y)>abs(x)&&abs(z)>threshold)
	{
		motor[leftMotor]=y+z;
		motor[rightMotor]=y-z;
	}
	else if(abs(z)>threshold)
	{
		motor[leftMotor]=z;
		motor[rightMotor]=-z;
	}
	else
	{
		motor[leftMotor]=0;
		motor[rightMotor]=0;
		motor[zMotor]=0;
	}
}

void pick()
{
	  motor[pickMotor]=vexRT[BtnRUp]*100-vexRT[BtnRDown]*100;
}

void hang()
{
	motor[larmMotor]=vexRT[BtnLUp]*100-vexRT[BtnLDown]*100;
	motor[rarmMotor]=vexRT[BtnLUp]*100-vexRT[BtnLDown]*100;
}

task one()
{
	while(1)
	{
		pick();
	}
}
task two()
{
	while(1)
	{
		hang();
		remove();
	}
}
task main()
{
	startTask(two);
	startTask(one);
	while(1){}
}
