#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor2,          zMotor,        tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor7,          pickMotor,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor9,          mMotor,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor12,         harmMotor,     tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int threshold=35;
int d=210;
int ttt=5000;
//int arm1_encoder=0;
//int arm2_encoder=0;
/*void resetEncoder()
{
   resetMotorEncoder(pickMotor);
   resetMotorEncoder(larmMotor);
   resetMotorEncoder(rarmMotor);
}
void getencoder()
{
	arm1_encoder=-getMotorEncoder(larmMotor);
  arm2_encoder=getMotorEncoder(rarmMotor);
}*/
void remove()
{
	int x=vexRT[ChC];
	int y=vexRT[ChD];
	int z=vexRT[ChB];

	if(abs(x)>threshold&&abs(x)>abs(y))
	{
		motor[zMotor]=x;
	}
	else if(abs(y)>threshold&&abs(y)>abs(x)&&abs(z)<threshold)
	{
		motor[leftMotor]=y;
		motor[rightMotor]=y;
	}
	else if(abs(y)>threshold&&abs(y)>abs(x)&&abs(z)>threshold)
	{
		motor[leftMotor]=y+z;
		motor[rightMotor]=y-z;
	}
	else if(abs(z)>threshold)
	{
		motor[leftMotor]=z;
		motor[rightMotor]=-z;
	}
	else
	{
		motor[leftMotor]=0;
		motor[rightMotor]=0;
		motor[zMotor]=0;
	}
}

void pick()
{
	  motor[pickMotor]=vexRT[BtnRUp]*100-vexRT[BtnRDown]*100;
}
void higharm()
{
	motor[harmMotor]=vexRT[BtnLUp]*100-vexRT[BtnLDown]*100;

}
task pickball()
{while(1)
{
	remove();
	pick();
	higharm();
}
}
task moveball()
{while(1)
{
	if(vexRT[BtnEUp]==1)
	{
		motor[mMotor]=100;
	}
	else if(vexRT[BtnEDown]==1)
	{
		motor[mMotor]=-100;
	}
	else if(vexRT[BtnFUp]==1)
	{
		clearTimer(T1);
		resetMotorEncoder(mMotor);
		while(abs(getMotorEncoder(mMotor))<d&&time1(T1)<(ttt))
		{
			motor[mMotor]=100;
		}
	}
	else if(vexRT[BtnFDown]==1)
	{
		clearTimer(T1);
		resetMotorEncoder(mMotor);
			while(abs(getMotorEncoder(mMotor))<d&&time1(T1)<(ttt))
		{
			motor[mMotor]=-100;
		}
	}
	else
	{
		motor[mMotor]=0;
	}
}
}
task main()
{
	startTask(moveball);
	startTask(pickball);
	while(1){}
}
